### ISSUE TITLE
iOS 11 & Swift 4 - The Complete iOS App Development Bootcamp

### ISSUE THREAD

**Issue by rudrankriyam** [snuff4/iOS-Projects#2]
Complete iOS 11 & Swift 4 - The Complete iOS App Development Bootcamp on [Udemy](https://www.udemy.com/ios-11-app-development-bootcamp/)
- [x] Getting Started with iOS 11 and Swift 4
- [x] iOS Interface Builder - The $999 App
- [x] Sideloading in iOS
- [x] Coding Challenge #1 - Using Interface Builder in Xcode
- [ ] Build a iOS Dice App to Learn Swift Programming Basics
- [x] Coding Challenge #2 - Swift Data Types, Variables and Arrays
- [x] Programming in Swift 4 for Beginners [Using Swift Playgrounds]
- [ ] Apple iOS APIs - Make a Music App
- [ ] The Model-View-Controller (MVC) Design Pattern - Make a Quiz App
- [x] Coding Challenge #3 - Control Flow - Build a Story App Like Lifeline
- [ ] iOS Auto Layout and Setting Constraints
- [ ] Programming in Swift 4 for Intermediates
- [ ] Cocoapods, GPS, APIs, REST and Getting Web Content - Weather App
- [ ] The Command Line and Terminal
- [ ] Coding Challenge #4 - Cocoapods, REST, APIs - Build a Bitcoin Price Tracker
- [ ] Cloud Database, iOS Animations and Advanced Swift - Make a WhatsApp Clone
- [ ] Firebase Version 3
- [ ] Git, GitHub and Version Control
- [ ] Core Data, Realm, User Defaults - Learn Persistent Local Data Storage - Todoey
- [ ] Introduction to Machine Learning
- [ ] iOS 11 - CoreML - How to Incorporate Machine Learning into Your iOS Apps
- [ ] [Optional Bonus Project] Machine Learning Using IBM Watson
- [ ] iOS 11 - Advanced CoreML - How to Convert Pre-Trained Models Using CoreML Tools
- [ ] iOS 11 - ARKit - How to Make Augmented Reality Apps in iOS
- [ ] [Bonus Project 2] - Make an Augmented Reality Pokemon Go app Using Vuforia
- [ ] iOS 11 - Advanced ARKit - How to Measure Real World Dimensions in an ARKit app
- [ ] How to Submit Your App to the App Store
- [ ] Next Steps
- [ ] The Complete App Design Course
- [ ] Colour Theory
- [ ] Typography
- [ ] The Fundamentals of User Interface (UI) Design for Mobile
- [ ] The Fundamentals of User Experience (UX) Design for Mobile
- [ ] Designing for IOS vs. Android - What are the Important Differences?
- [ ] A Step-By-Step Guide to a Professional Mobile Designer's Workflow
- [ ] Design Resources
- [ ] The Complete App Marketing Course - How to Make Money From Your Apps
- [ ] Idea Validation - Save Yourself Time and Money
- [ ] App Monetisation Methods - How to Make Money From Your App
- [ ] How to Optimise Your App Store Listing
- [ ] Growth Hacking Techniques for App Downloads
- [ ] How to Get Press Coverage for Your App
- [ ] How to Get Your App Featured on the App Store
- [ ] App Store Optimisation - How to Rank Higher on the App Store Search Algorithm
- [ ] The Right Way of Using Paid Advertising to Drive App Downloads
- [ ] App Store Reviews and Ratings
- [ ] How to Use App Analytics to Increase User Retention
- [ ] White Hat vs. Black Hat Methods of Getting More App Downloads and Revenue
- [ ] Bonus: How to Build Your App Showcase Website
